### ISSUE TITLE
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

### ISSUE THREAD

**Issue by JosephKarpinski** [jpdeleon/quicklook#10]
This worked before. Stopped working.

from quicklook import TessQuickLook

eb = TessQuickLook(target_name="TIC 52005579")

Generating TQL for TIC 52005579...
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
File /opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1344, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   [1343](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1343) try:
-> [1344](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1344)     h.request(req.get_method(), req.selector, req.data, headers,
   [1345](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1345)               encode_chunked=req.has_header('Transfer-encoding'))
   [1346](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1346) except OSError as err: # timeout error

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1336, in HTTPConnection.request(self, method, url, body, headers, encode_chunked)
   [1335](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1335) """Send a complete request to the server."""
-> [1336](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1336) self._send_request(method, url, body, headers, encode_chunked)

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1382, in HTTPConnection._send_request(self, method, url, body, headers, encode_chunked)
   [1381](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1381)     body = _encode(body, 'body')
-> [1382](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1382) self.endheaders(body, encode_chunked=encode_chunked)

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1331, in HTTPConnection.endheaders(self, message_body, encode_chunked)
   [1330](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1330)     raise CannotSendHeader()
-> [1331](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1331) self._send_output(message_body, encode_chunked=encode_chunked)

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1091, in HTTPConnection._send_output(self, message_body, encode_chunked)
   [1090](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1090) del self._buffer[:]
-> [1091](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1091) self.send(msg)
   [1093](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1093) if message_body is not None:
   [1094](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1094) 
   [1095](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1095)     # create a consistent interface to message_body

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1035, in HTTPConnection.send(self, data)
   [1034](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1034) if self.auto_open:
-> [1035](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1035)     self.connect()
   [1036](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1036) else:

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1470, in HTTPSConnection.connect(self)
   [1468](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1468) "Connect to a host on a given (SSL) port."
-> [1470](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1470) super().connect()
   [1472](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1472) if self._tunnel_host:

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1001, in HTTPConnection.connect(self)
   [1000](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1000) sys.audit("http.client.connect", self, self.host, self.port)
-> [1001](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1001) self.sock = self._create_connection(
   [1002](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1002)     (self.host,self.port), self.timeout, self.source_address)
   [1003](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py:1003) # Might fail in OSs that don't implement TCP_NODELAY

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py:828, in create_connection(address, timeout, source_address, all_errors)
    [827](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py:827) exceptions = []
--> [828](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py:828) for res in getaddrinfo(host, port, 0, SOCK_STREAM):
    [829](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py:829)     af, socktype, proto, canonname, sa = res

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py:963, in getaddrinfo(host, port, family, type, proto, flags)
    [962](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py:962) addrlist = []
--> [963](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py:963) for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    [964](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py:964)     af, socktype, proto, canonname, sa = res

gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
Cell In[531], [line 3](vscode-notebook-cell:?execution_count=531&line=3)
      [1](vscode-notebook-cell:?execution_count=531&line=1) from quicklook import TessQuickLook
----> [3](vscode-notebook-cell:?execution_count=531&line=3) eb = TessQuickLook(target_name="TIC 52005579")
      [4](vscode-notebook-cell:?execution_count=531&line=4) #eb = TessQuickLook(target_name="TIC 52005579", sector=70, pipeline="qlp")

File ~/src/quicklook/quicklook/tql.py:83, in TessQuickLook.__init__(self, target_name, sector, pipeline, flux_type, exptime, pg_method, flatten_method, gp_kernel, gp_kernel_size, window_length, edge_cutoff, sigma_clip_raw, sigma_clip_flat, custom_ephem, mask_ephem, Porb_limits, archival_survey, plot, savefig, savetls, overwrite, outdir)
     [81](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:81) self.target_name = target_name
     [82](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:82) print(f"Generating TQL for {self.target_name}...")
---> [83](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:83) self.tfop_info = get_tfop_info(target_name)
     [84](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:84) self.star_names = np.array(
     [85](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:85)     self.tfop_info.get("basic_info")["star_names"].split(", ")
     [86](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:86) )
     [87](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:87) self.gaia_name = self.star_names[
     [88](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:88)     np.array([i[:4].lower() == "gaia" for i in self.star_names])
     [89](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/tql.py:89) ][0]

File ~/src/quicklook/quicklook/utils.py:116, in get_tfop_info(target_name)
    [114](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/utils.py:114) base_url = "https://exofop.ipac.caltech.edu/tess"
    [115](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/utils.py:115) url = f"{base_url}/target.php?id={target_name.replace(' ','')}&json"
--> [116](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/utils.py:116) response = urlopen(url)
    [117](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/utils.py:117) assert response.code == 200, "Failed to get data from ExoFOP-TESS"
    [118](https://file+.vscode-resource.vscode-cdn.net/Users/josephkarpinski/Documents/MyPython/Gaia%20DR3%20GitHub/~/src/quicklook/quicklook/utils.py:118) try:

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:215, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    [213](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:213) else:
    [214](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:214)     opener = _opener
--> [215](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:215) return opener.open(url, data, timeout)

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:515, in OpenerDirector.open(self, fullurl, data, timeout)
    [512](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:512)     req = meth(req)
    [514](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:514) sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> [515](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:515) response = self._open(req, data)
    [517](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:517) # post-process response
    [518](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:518) meth_name = protocol+"_response"

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:532, in OpenerDirector._open(self, req, data)
    [529](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:529)     return result
    [531](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:531) protocol = req.type
--> [532](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:532) result = self._call_chain(self.handle_open, protocol, protocol +
    [533](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:533)                           '_open', req)
    [534](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:534) if result:
    [535](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:535)     return result

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:492, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    [490](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:490) for handler in handlers:
    [491](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:491)     func = getattr(handler, meth_name)
--> [492](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:492)     result = func(*args)
    [493](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:493)     if result is not None:
    [494](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:494)         return result

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1392, in HTTPSHandler.https_open(self, req)
   [1391](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1391) def https_open(self, req):
-> [1392](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1392)     return self.do_open(http.client.HTTPSConnection, req,
   [1393](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1393)                         context=self._context)

File /opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1347, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   [1344](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1344)         h.request(req.get_method(), req.selector, req.data, headers,
   [1345](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1345)                   encode_chunked=req.has_header('Transfer-encoding'))
   [1346](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1346)     except OSError as err: # timeout error
-> [1347](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1347)         raise URLError(err)
   [1348](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1348)     r = h.getresponse()
   [1349](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py:1349) except:

URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by JosephKarpinski** [comment]
Worked before, now...

/Users/josephkarpinski/Downloads/quicklook-main-4/scripts/ql --name "TIC 198457103" --sector 78 --pipeline 'spoc'
Generating TQL for TIC 198457103...
Traceback (most recent call last):
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py", line 828, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/josephkarpinski/Downloads/quicklook-main-4/scripts/ql", line 230, in <module>
    ql = TessQuickLook(
         ^^^^^^^^^^^^^^
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 83, in __init__
    self.tfop_info = get_tfop_info(target_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josephkarpinski/src/quicklook/quicklook/utils.py", line 116, in get_tfop_info
    response = urlopen(url)
               ^^^^^^^^^^^^
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by JosephKarpinski** [comment]
The above error happened on an M1 iMac.

On a Intel iMac:

conda activate envQuicklook4                              
(envQuicklook4) josephkarpinski@Josephs-iMac ~ % cd /Users/josephkarpinski/Downloads/quicklook-main/scripts
(envQuicklook4) josephkarpinski@Josephs-iMac scripts % ./ql -name "TIC 198457103" -sec 80 -p 'spoc'              
/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/site-packages/lightkurve/config/__init__.py:119: UserWarning: The default Lightkurve cache directory, used by download(), etc., has been moved to /Users/josephkarpinski/.lightkurve/cache. Please move all the files in the legacy directory /Users/josephkarpinski/.lightkurve-cache to the new location and remove the legacy directory. Refer to https://docs.lightkurve.org/reference/config.html#default-cache-directory-migration for more information.
  warnings.warn(
Generating TQL for TIC 198457103...
Traceback (most recent call last):
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/josephkarpinski/Downloads/quicklook-main/scripts/./ql", line 225, in <module>
    ql = TessQuickLook(
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 83, in __init__
    self.tfop_info = get_tfop_info(target_name)
  File "/Users/josephkarpinski/src/quicklook/quicklook/utils.py", line 25, in get_tfop_info
    response = urlopen(url)
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/josephkarpinski/anaconda3/envs/envQuicklook4/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by jpdeleon** [comment]
This was a temporary server query issue. Closing now.
