### ISSUE TITLE
quicklook-1.1  - ModuleNotFoundError: No module named 'transitleastsquares'

### ISSUE THREAD

**Issue by JosephKarpinski** [jpdeleon/quicklook#7]
(base) josephkarpinski@Josephs-iMac-2 ~ % conda activate envM1v3123      
(envM1v3123) josephkarpinski@Josephs-iMac-2 ~ % pip install -e git+https://github.com/jpdeleon/quicklook.git#egg=quicklook 
Obtaining quicklook from git+https://github.com/jpdeleon/quicklook.git#egg=quicklook
  Updating ./src/quicklook clone
  Running command git fetch -q --tags
  Running command git reset --hard -q f966209ff02c1c3646f44cc4d36a539eb373fd2b
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: quicklook
  Building editable for quicklook (pyproject.toml) ... done
  Created wheel for quicklook: filename=quicklook-1.1-0.editable-py3-none-any.whl size=21424 sha256=f26321a32b16fb756497f15aa11dd545065d9ac00c7c7c1640af8d55d6101e80
  Stored in directory: /private/var/folders/c2/y73585dd0g1bnbknv863zg5r0000gn/T/pip-ephem-wheel-cache-kcv8won2/wheels/a9/81/c7/b5ab8820c59d86be7937fb1740a7343ea089664650b0b692ff
Successfully built quicklook
Installing collected packages: quicklook
Successfully installed quicklook-1.1

(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % cd /Users/josephkarpinski/Downloads/quicklook-main-4/scripts 
(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % ./ql --name TOI-1150                                         
Traceback (most recent call last):
  File "/Users/josephkarpinski/Downloads/quicklook-main-4/scripts/./ql", line 6, in <module>
    from quicklook.tql import TessQuickLook
  File "/Users/josephkarpinski/src/quicklook/quicklook/__init__.py", line 9, in <module>
    from .tql import *
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 12, in <module>
    from transitleastsquares import transitleastsquares as tls
ModuleNotFoundError: No module named 'transitleastsquares'
(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts %

**Comment by JosephKarpinski** [comment]
PIP installed missing module:

(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % pip install transitleastsquares 
Collecting transitleastsquares
  Downloading transitleastsquares-1.32-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: astroquery>=0.3.9 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from transitleastsquares) (0.4.7)
Requirement already satisfied: numpy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from transitleastsquares) (1.26.4)
Collecting numba (from transitleastsquares)
  Downloading numba-0.60.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
Requirement already satisfied: tqdm in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from transitleastsquares) (4.66.4)
Collecting batman-package (from transitleastsquares)
  Using cached batman-package-2.4.9.tar.gz (394 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting configparser (from transitleastsquares)
  Downloading configparser-7.1.0-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: astropy>=4.2.1 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astroquery>=0.3.9->transitleastsquares) (6.1.0)
Requirement already satisfied: requests>=2.19 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astroquery>=0.3.9->transitleastsquares) (2.32.3)
Requirement already satisfied: beautifulsoup4>=4.8 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astroquery>=0.3.9->transitleastsquares) (4.12.3)
Requirement already satisfied: html5lib>=0.999 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astroquery>=0.3.9->transitleastsquares) (1.1)
Requirement already satisfied: keyring>=15.0 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astroquery>=0.3.9->transitleastsquares) (25.2.1)
Requirement already satisfied: pyvo>=1.1 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astroquery>=0.3.9->transitleastsquares) (1.5.2)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba->transitleastsquares)
  Downloading llvmlite-0.43.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.8 kB)
Requirement already satisfied: pyerfa>=2.0.1.1 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astropy>=4.2.1->astroquery>=0.3.9->transitleastsquares) (2.0.1.4)
Requirement already satisfied: astropy-iers-data>=0.2024.4.29.0.28.48 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astropy>=4.2.1->astroquery>=0.3.9->transitleastsquares) (0.2024.6.10.0.30.47)
Requirement already satisfied: PyYAML>=3.13 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astropy>=4.2.1->astroquery>=0.3.9->transitleastsquares) (6.0.1)
Requirement already satisfied: packaging>=19.0 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from astropy>=4.2.1->astroquery>=0.3.9->transitleastsquares) (24.1)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from beautifulsoup4>=4.8->astroquery>=0.3.9->transitleastsquares) (2.5)
Requirement already satisfied: six>=1.9 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from html5lib>=0.999->astroquery>=0.3.9->transitleastsquares) (1.16.0)
Requirement already satisfied: webencodings in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from html5lib>=0.999->astroquery>=0.3.9->transitleastsquares) (0.5.1)
Requirement already satisfied: jaraco.classes in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from keyring>=15.0->astroquery>=0.3.9->transitleastsquares) (3.4.0)
Requirement already satisfied: jaraco.functools in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from keyring>=15.0->astroquery>=0.3.9->transitleastsquares) (4.0.1)
Requirement already satisfied: jaraco.context in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from keyring>=15.0->astroquery>=0.3.9->transitleastsquares) (5.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from requests>=2.19->astroquery>=0.3.9->transitleastsquares) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from requests>=2.19->astroquery>=0.3.9->transitleastsquares) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from requests>=2.19->astroquery>=0.3.9->transitleastsquares) (1.26.19)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from requests>=2.19->astroquery>=0.3.9->transitleastsquares) (2024.6.2)
Requirement already satisfied: more-itertools in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from jaraco.classes->keyring>=15.0->astroquery>=0.3.9->transitleastsquares) (10.3.0)
Downloading transitleastsquares-1.32-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.5/47.5 kB 1.0 MB/s eta 0:00:00
Downloading configparser-7.1.0-py3-none-any.whl (17 kB)
Downloading numba-0.60.0-cp312-cp312-macosx_11_0_arm64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 6.2 MB/s eta 0:00:00
Downloading llvmlite-0.43.0-cp312-cp312-macosx_11_0_arm64.whl (28.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.8/28.8 MB 6.7 MB/s eta 0:00:00
Building wheels for collected packages: batman-package
  Building wheel for batman-package (pyproject.toml) ... done
  Created wheel for batman-package: filename=batman_package-2.4.9-cp312-cp312-macosx_11_0_arm64.whl size=55976 sha256=81e791f1cf9f6e56ed9bf303d3ce5656e70f039088246459a8cdb5953a4bb8d6
  Stored in directory: /Users/josephkarpinski/Library/Caches/pip/wheels/7e/3d/0e/36a1286d22ad6f0d361949daec89867b1b8780a176e6002488
Successfully built batman-package
Installing collected packages: llvmlite, configparser, batman-package, numba, transitleastsquares
Successfully installed batman-package-2.4.9 configparser-7.1.0 llvmlite-0.43.0 numba-0.60.0 transitleastsquares-1.32
(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % 

but got: 

(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % ./ql --name TOI-1150            
Traceback (most recent call last):
  File "/Users/josephkarpinski/Downloads/quicklook-main-4/scripts/./ql", line 6, in <module>
    from quicklook.tql import TessQuickLook
  File "/Users/josephkarpinski/src/quicklook/quicklook/__init__.py", line 9, in <module>
    from .tql import *
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 13, in <module>
    from wotan import flatten
ModuleNotFoundError: No module named 'wotan'

**Comment by JosephKarpinski** [comment]
PIP installed: 

(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % pip install wotan 
Collecting wotan
  Using cached wotan-1.10-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from wotan) (1.26.4)
Requirement already satisfied: numba in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from wotan) (0.60.0)
Requirement already satisfied: scipy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from wotan) (1.13.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from numba->wotan) (0.43.0)
Using cached wotan-1.10-py3-none-any.whl (30 kB)
Installing collected packages: wotan
Successfully installed wotan-1.10

but got: 

(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % pip install wotan 
Collecting wotan
  Using cached wotan-1.10-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from wotan) (1.26.4)
Requirement already satisfied: numba in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from wotan) (0.60.0)
Requirement already satisfied: scipy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from wotan) (1.13.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from numba->wotan) (0.43.0)
Using cached wotan-1.10-py3-none-any.whl (30 kB)
Installing collected packages: wotan
Successfully installed wotan-1.10
(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % ./ql --name TOI-1150
Traceback (most recent call last):
  File "/Users/josephkarpinski/Downloads/quicklook-main-4/scripts/./ql", line 6, in <module>
    from quicklook.tql import TessQuickLook
  File "/Users/josephkarpinski/src/quicklook/quicklook/__init__.py", line 9, in <module>
    from .tql import *
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 20, in <module>
    from aesthetic.plot import set_style
ModuleNotFoundError: No module named 'aesthetic'

**Comment by JosephKarpinski** [comment]
PIP installed:

(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % pip install aesthetic 
Collecting aesthetic
  Using cached aesthetic-0.6.tar.gz (474 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from aesthetic) (1.26.4)
Requirement already satisfied: scipy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from aesthetic) (1.13.1)
Requirement already satisfied: matplotlib in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from aesthetic) (3.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from matplotlib->aesthetic) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from matplotlib->aesthetic) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from matplotlib->aesthetic) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from matplotlib->aesthetic) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from matplotlib->aesthetic) (24.1)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from matplotlib->aesthetic) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from matplotlib->aesthetic) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from matplotlib->aesthetic) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib->aesthetic) (1.16.0)
Building wheels for collected packages: aesthetic
  Building wheel for aesthetic (setup.py) ... done
  Created wheel for aesthetic: filename=aesthetic-0.6-py3-none-any.whl size=5937 sha256=d9ddbb83d91c3162d06d26145739d31bdf1de9d7b5c732918eea7350493ea36b
  Stored in directory: /Users/josephkarpinski/Library/Caches/pip/wheels/f8/58/10/04456608155c37c38a0989e2c2e11dddb0b8b13114bc7b8435
Successfully built aesthetic
Installing collected packages: aesthetic
Successfully installed aesthetic-0.6

but got:

Traceback (most recent call last):
  File "/Users/josephkarpinski/Downloads/quicklook-main-4/scripts/./ql", line 6, in <module>
    from quicklook.tql import TessQuickLook
  File "/Users/josephkarpinski/src/quicklook/quicklook/__init__.py", line 9, in <module>
    from .tql import *
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 22, in <module>
    import flammkuchen as fk
ModuleNotFoundError: No module named 'flammkuchen'

**Comment by JosephKarpinski** [comment]
PIP installed:

(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % pip install flammkuchen 
Collecting flammkuchen
  Using cached flammkuchen-1.0.3-py2.py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: numpy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from flammkuchen) (1.26.4)
Requirement already satisfied: scipy in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from flammkuchen) (1.13.1)
Requirement already satisfied: tables in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from flammkuchen) (3.9.2)
Requirement already satisfied: numexpr>=2.6.2 in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from tables->flammkuchen) (2.10.0)
Requirement already satisfied: packaging in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from tables->flammkuchen) (24.1)
Requirement already satisfied: py-cpuinfo in /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages (from tables->flammkuchen) (9.0.0)
Using cached flammkuchen-1.0.3-py2.py3-none-any.whl (16 kB)
Installing collected packages: flammkuchen
Successfully installed flammkuchen-1.0.3 

but got:

(envM1v3123) josephkarpinski@Josephs-iMac-2 scripts % ./ql --name TOI-1150    
Traceback (most recent call last):
  File "/Users/josephkarpinski/Downloads/quicklook-main-4/scripts/./ql", line 6, in <module>
    from quicklook.tql import TessQuickLook
  File "/Users/josephkarpinski/src/quicklook/quicklook/__init__.py", line 9, in <module>
    from .tql import *
  File "/Users/josephkarpinski/src/quicklook/quicklook/tql.py", line 22, in <module>
    import flammkuchen as fk
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages/flammkuchen/__init__.py", line 6, in <module>
    from flammkuchen.hdf5io import (
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages/flammkuchen/hdf5io.py", line 4, in <module>
    import tables
  File "/opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages/tables/__init__.py", line 44, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: dlopen(/opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages/tables/utilsextension.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libblosc2.2.dylib
  Referenced from: <E432A0B5-F120-3611-A1F7-7AE9D3F36459> /opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages/tables/utilsextension.cpython-312-darwin.so
  Reason: tried: '/opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages/tables/../../../libblosc2.2.dylib' (no such file), '/opt/anaconda3/envs/envM1v3123/lib/python3.12/site-packages/tables/../../../libblosc2.2.dylib' (no such file), '/opt/anaconda3/envs/envM1v3123/bin/../lib/libblosc2.2.dylib' (no such file), '/opt/anaconda3/envs/envM1v3123/bin/../lib/libblosc2.2.dylib' (no such file), '/usr/local/lib/libblosc2.2.dylib' (no such file), '/usr/lib/libblosc2.2.dylib' (no such file, not in dyld cache)

**Comment by JosephKarpinski** [comment]
This fixed it. conda install -c conda-forge c-blosc2=2.13
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/envM1v3123

  added / updated specs:
    - c-blosc2=2.13


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    c-blosc2-2.13.2            |       ha57e6be_1         233 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         233 KB

The following packages will be DOWNGRADED:

  c-blosc2                                2.14.4-ha57e6be_1 --> 2.13.2-ha57e6be_1 


Proceed ([y]/n)? y


Downloading and Extracting Packages:
                                                                                                                                    
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Resolved
